name: 🐞 Bug report
description: Write a report to help improve Nuxt Gtag
labels: [pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Please use a template below to create a minimal reproduction:
        👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
        👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox
  - type: textarea
    id: bug-env
    attributes:
      label: Environment
      description: You can use `npx nuxt info` to fill this section.
      placeholder: Environment
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a repo that can reproduce the problem you ran into. A [**minimal reproduction**](https://nuxt.com/docs/community/reporting-bugs#create-a-minimal-reproduction) is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to file a PR for this issue, please let us know in the description. Thanks a lot!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: additonal
    attributes:
      label: Additional context
      description: If applicable, add any other context about the problem here.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Optional if reproduction is provided. Please try not to insert an image, but copy and paste the log text.
      render: shell-script
